###
## errors.py
class DomainError(Exception): ...
class ConfigError(DomainError): ...
class ValidationError(DomainError): ...
class DataError(DomainError): ...
class DbError(DomainError): ...
class EtlError(DomainError): ...

