#########
## db.py

from typing import Protocol, Optional
import pandas as pd

class DbPort(Protocol):
    def execute_ddl(self, ddl_sql: str) -> None: ...
    def exec_sql(self, sql: str, params: Optional[dict] = None) -> None: ...
    def read_sql(self, sql: str, params: Optional[dict] = None) -> pd.DataFrame: ...
    def write_df(self, table: str, df: pd.DataFrame, schema: str = "dbo") -> None: ...
